package com.dreyer.coffeemasters.ui.theme

import androidx.compose.ui.graphics.Color

/*val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

// Colors are ARGB - 0xFF....
val Primary = Color(0xFF43281C)
val Secondary = Color(0xFF333D29)
val Ternary = Color(0xFF7F4F24)
val Alternative1 = Color(0xFFB08968)
val Alternative2 = Color(0xFFDDB892)
val CardBackground = Color(0xFFEDE0D4)
val SurfaceBackground = Color(0xFFEFEFEF)
val OnPrimary = Color.Yellow*/

// Generate via material 3 theme builder
//https://m3.material.io/theme-builder#/custom

val md_theme_light_primary = Color(0xFF99461C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCD)
val md_theme_light_onPrimaryContainer = Color(0xFF360F00)
val md_theme_light_secondary = Color(0xFF8C5000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCBF)
val md_theme_light_onSecondaryContainer = Color(0xFF2D1600)
val md_theme_light_tertiary = Color(0xFF675F30)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEFE3A9)
val md_theme_light_onTertiaryContainer = Color(0xFF201C00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFF5DED5)
val md_theme_light_onSurfaceVariant = Color(0xFF53443D)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
val md_theme_light_inverseSurface = Color(0xFF362F2C)
val md_theme_light_inversePrimary = Color(0xFFFFB596)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF99461C)
val md_theme_light_outlineVariant = Color(0xFFD8C2BA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB596)
val md_theme_dark_onPrimary = Color(0xFF581E00)
val md_theme_dark_primaryContainer = Color(0xFF7A2F05)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCD)
val md_theme_dark_secondary = Color(0xFFFFB872)
val md_theme_dark_onSecondary = Color(0xFF4A2800)
val md_theme_dark_secondaryContainer = Color(0xFF6A3B00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBF)
val md_theme_dark_tertiary = Color(0xFFD2C78F)
val md_theme_dark_onTertiary = Color(0xFF373106)
val md_theme_dark_tertiaryContainer = Color(0xFF4E471B)
val md_theme_dark_onTertiaryContainer = Color(0xFFEFE3A9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DB)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DB)
val md_theme_dark_surfaceVariant = Color(0xFF53443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BA)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DB)
val md_theme_dark_inversePrimary = Color(0xFF99461C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB596)
val md_theme_dark_outlineVariant = Color(0xFF53443D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF502815)
